name: Sync wiki
on:
  push:
    branches:  
      - "main" 
    paths: 
      - "docs/wiki/**" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repo 
        uses: actions/checkout@v4

      # Setup git credentials 
      - name: Setup git 
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # clone the wiki and sync the wiki folder from the main repo to the wiki repo
      - name: Sync the wiki
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone  https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki-repo
          rsync -avh --exclude '.git' --delete docs/wiki/ wiki-repo/ 
          cd wiki-repo
          git add . 
          git commit -m "Sync wiki folder from main"
          git push
